export const navLinks = [
    {
        id:1,
        url:"#",
        label:"Home"
    },
    {
        id:2,
        url:"#About",
        label:"About"
    },
    {
        id:3,
        url:"#Services",
        label:"Services"
    },
    {
        id:4,
        url:"#Projects",
        label:"Projects"
    },
    {
        id:5,
        url:"#Contacts",
        label:"Contacts"
    },
]